### ISSUE TITLE
Error when no moves are available to be made

### ISSUE THREAD

**Issue by scsewell** [kiankd/comp424#1]
On the server, there seems to be no handling of the case when a player has no valid move. This causes a crash since the server will attempt to randomly pick a move as the player can't supply a valid move, but none exist. I've attached a game log demonstrating the case where I encountered the error.
[game00007.log](https://github.com/kiankd/comp424/files/1809546/game00007.log)

I was unable to find any mention in the rules of what should happen when no move can be made. Should we assume a loss for the player with no move?

**Comment by kiankd** [comment]
Thanks for noting this. I'll update the code soon to account for this. If this occurs, the person who does not have any legal moves will be considered to have lost.

**Comment by kiankd** [comment]
Fixed with latest commit.
